repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: debug-statements
    -   id: name-tests-test
        args: ['--pytest-test-first']

-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        args: ['--line-length=120']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    -   id: mypy
        additional_dependencies: [types-cryptography, types-setuptools]
        args: [--ignore-missing-imports, --no-strict-optional, --disable-error-code=no-any-return]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
    -   id: bandit
        args: ['-c', 'pyproject.toml', '--severity-level', 'medium']
        additional_dependencies: ['bandit[toml]']
